/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta1"
	scheme "github.com/longhorn/longhorn-manager/k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BackupStoreBackupVolumesGetter has a method to return a BackupStoreBackupVolumeInterface.
// A group's client should implement this interface.
type BackupStoreBackupVolumesGetter interface {
	BackupStoreBackupVolumes(namespace string) BackupStoreBackupVolumeInterface
}

// BackupStoreBackupVolumeInterface has methods to work with BackupStoreBackupVolume resources.
type BackupStoreBackupVolumeInterface interface {
	Create(*v1beta1.BackupStoreBackupVolume) (*v1beta1.BackupStoreBackupVolume, error)
	Update(*v1beta1.BackupStoreBackupVolume) (*v1beta1.BackupStoreBackupVolume, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.BackupStoreBackupVolume, error)
	List(opts v1.ListOptions) (*v1beta1.BackupStoreBackupVolumeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackupStoreBackupVolume, err error)
	BackupStoreBackupVolumeExpansion
}

// backupStoreBackupVolumes implements BackupStoreBackupVolumeInterface
type backupStoreBackupVolumes struct {
	client rest.Interface
	ns     string
}

// newBackupStoreBackupVolumes returns a BackupStoreBackupVolumes
func newBackupStoreBackupVolumes(c *LonghornV1beta1Client, namespace string) *backupStoreBackupVolumes {
	return &backupStoreBackupVolumes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backupStoreBackupVolume, and returns the corresponding backupStoreBackupVolume object, and an error if there is any.
func (c *backupStoreBackupVolumes) Get(name string, options v1.GetOptions) (result *v1beta1.BackupStoreBackupVolume, err error) {
	result = &v1beta1.BackupStoreBackupVolume{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackupStoreBackupVolumes that match those selectors.
func (c *backupStoreBackupVolumes) List(opts v1.ListOptions) (result *v1beta1.BackupStoreBackupVolumeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.BackupStoreBackupVolumeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backupStoreBackupVolumes.
func (c *backupStoreBackupVolumes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a backupStoreBackupVolume and creates it.  Returns the server's representation of the backupStoreBackupVolume, and an error, if there is any.
func (c *backupStoreBackupVolumes) Create(backupStoreBackupVolume *v1beta1.BackupStoreBackupVolume) (result *v1beta1.BackupStoreBackupVolume, err error) {
	result = &v1beta1.BackupStoreBackupVolume{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		Body(backupStoreBackupVolume).
		Do().
		Into(result)
	return
}

// Update takes the representation of a backupStoreBackupVolume and updates it. Returns the server's representation of the backupStoreBackupVolume, and an error, if there is any.
func (c *backupStoreBackupVolumes) Update(backupStoreBackupVolume *v1beta1.BackupStoreBackupVolume) (result *v1beta1.BackupStoreBackupVolume, err error) {
	result = &v1beta1.BackupStoreBackupVolume{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		Name(backupStoreBackupVolume.Name).
		Body(backupStoreBackupVolume).
		Do().
		Into(result)
	return
}

// Delete takes name of the backupStoreBackupVolume and deletes it. Returns an error if one occurs.
func (c *backupStoreBackupVolumes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backupStoreBackupVolumes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched backupStoreBackupVolume.
func (c *backupStoreBackupVolumes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackupStoreBackupVolume, err error) {
	result = &v1beta1.BackupStoreBackupVolume{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backupstorebackupvolumes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
