/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupStoreBackupVolumes implements BackupStoreBackupVolumeInterface
type FakeBackupStoreBackupVolumes struct {
	Fake *FakeLonghornV1beta1
	ns   string
}

var backupstorebackupvolumesResource = schema.GroupVersionResource{Group: "longhorn.io", Version: "v1beta1", Resource: "backupstorebackupvolumes"}

var backupstorebackupvolumesKind = schema.GroupVersionKind{Group: "longhorn.io", Version: "v1beta1", Kind: "BackupStoreBackupVolume"}

// Get takes name of the backupStoreBackupVolume, and returns the corresponding backupStoreBackupVolume object, and an error if there is any.
func (c *FakeBackupStoreBackupVolumes) Get(name string, options v1.GetOptions) (result *v1beta1.BackupStoreBackupVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backupstorebackupvolumesResource, c.ns, name), &v1beta1.BackupStoreBackupVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupStoreBackupVolume), err
}

// List takes label and field selectors, and returns the list of BackupStoreBackupVolumes that match those selectors.
func (c *FakeBackupStoreBackupVolumes) List(opts v1.ListOptions) (result *v1beta1.BackupStoreBackupVolumeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backupstorebackupvolumesResource, backupstorebackupvolumesKind, c.ns, opts), &v1beta1.BackupStoreBackupVolumeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BackupStoreBackupVolumeList{ListMeta: obj.(*v1beta1.BackupStoreBackupVolumeList).ListMeta}
	for _, item := range obj.(*v1beta1.BackupStoreBackupVolumeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupStoreBackupVolumes.
func (c *FakeBackupStoreBackupVolumes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backupstorebackupvolumesResource, c.ns, opts))

}

// Create takes the representation of a backupStoreBackupVolume and creates it.  Returns the server's representation of the backupStoreBackupVolume, and an error, if there is any.
func (c *FakeBackupStoreBackupVolumes) Create(backupStoreBackupVolume *v1beta1.BackupStoreBackupVolume) (result *v1beta1.BackupStoreBackupVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backupstorebackupvolumesResource, c.ns, backupStoreBackupVolume), &v1beta1.BackupStoreBackupVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupStoreBackupVolume), err
}

// Update takes the representation of a backupStoreBackupVolume and updates it. Returns the server's representation of the backupStoreBackupVolume, and an error, if there is any.
func (c *FakeBackupStoreBackupVolumes) Update(backupStoreBackupVolume *v1beta1.BackupStoreBackupVolume) (result *v1beta1.BackupStoreBackupVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backupstorebackupvolumesResource, c.ns, backupStoreBackupVolume), &v1beta1.BackupStoreBackupVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupStoreBackupVolume), err
}

// Delete takes name of the backupStoreBackupVolume and deletes it. Returns an error if one occurs.
func (c *FakeBackupStoreBackupVolumes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backupstorebackupvolumesResource, c.ns, name), &v1beta1.BackupStoreBackupVolume{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupStoreBackupVolumes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backupstorebackupvolumesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.BackupStoreBackupVolumeList{})
	return err
}

// Patch applies the patch and returns the patched backupStoreBackupVolume.
func (c *FakeBackupStoreBackupVolumes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.BackupStoreBackupVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backupstorebackupvolumesResource, c.ns, name, pt, data, subresources...), &v1beta1.BackupStoreBackupVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupStoreBackupVolume), err
}
